import type { VenueSeed } from './venues';

// Gap-fill curated venues researched 2026-06 to address category coverage holes
// identified by the venue-quality audit:
//   - HCM bar/nightlife (had only 1 curated bar despite being the SE-Asia
//     nightlife capital)
//   - Đà Nẵng cafe (had only 1 curated cafe — catastrophic for the third
//     biggest city in VN)
//   - Hà Nội bar (zero curated bars; phố cổ Tạ Hiện zone alone deserves 10+)
//   - Đà Lạt viewpoint (4 curated; the city's whole identity is ngắm cảnh)
//   - Ninh Bình viewpoint (4 curated; UNESCO heritage should have ~15)
//   - Hội An walking-street + cafe (phố cổ underrepresented in curated data)
//   - HCM / Đà Nẵng / Vũng Tàu homestay (under 10 curated each)
//
// Imported via src/database/import-landmarks.ts — same merge logic as the
// original landmark-venues.ts, so re-runs are idempotent.

export const LANDMARK_VENUES_EXTRA: Record<string, VenueSeed[]> = {
  "ho-chi-minh": [
    // — BAR / NIGHTLIFE (20) —
    {"name":"Layla Eatery & Bar","category":"bar","district":"Quận 1","address":"63 Đông Du, Bến Nghé, Quận 1, TP.HCM","description":"Bar Trung Đông sang trọng giữa Quận 1 với cocktail signature và hookah, sân thượng nhìn ra Nhà thờ Đức Bà. Điểm hẹn của giới văn phòng và expat sau giờ làm.","tags":["Quán bar","cocktail","Middle Eastern","expat"],"hours":"17:00 - 02:00","priceRange":4,"lat":10.7785,"lng":106.7039},
    {"name":"Drinking & Healing","category":"bar","district":"Quận 1","address":"19 Tôn Thất Thiệp, Bến Nghé, Quận 1, TP.HCM","description":"Cocktail bar craft kín đáo trên đường Tôn Thất Thiệp, không gian mờ ảo và bartender pha chế tỉ mỉ. Lọt top 50 bar châu Á nhiều năm liền.","tags":["Quán bar cocktail","speakeasy","Asia 50 best"],"hours":"19:00 - 02:00","priceRange":4,"lat":10.7741,"lng":106.7019},
    {"name":"Stir Bar Saigon","category":"bar","district":"Quận 1","address":"6 Đỗ Quang Đẩu, Phạm Ngũ Lão, Quận 1, TP.HCM","description":"Cocktail bar nghệ thuật cạnh phố Tây Bùi Viện, signature menu lấy cảm hứng từ trái cây nhiệt đới Việt Nam. Không gian nhỏ ấm cúng, đầu bếp pha chế giải quốc tế.","tags":["Quán bar cocktail","tropical","craft"],"hours":"18:00 - 01:00","priceRange":3,"lat":10.7677,"lng":106.6929},
    {"name":"The Sanctuary Saigon","category":"bar","district":"Quận 1","address":"6 Đỗ Quang Đẩu, Phạm Ngũ Lão, Quận 1, TP.HCM","description":"Speakeasy ẩn sau cửa kệ sách, không gian xưa phong cách Phật giáo Á Đông. Cocktail kết hợp thảo mộc và rượu Việt như rượu nếp, sake.","tags":["Quán bar cocktail","speakeasy","Asian"],"hours":"19:00 - 02:00","priceRange":4,"lat":10.7676,"lng":106.6929},
    {"name":"Heart of Darkness Brewery","category":"bar","district":"Quận 1","address":"31D Lý Tự Trọng, Bến Nghé, Quận 1, TP.HCM","description":"Brewery thủ công lớn nhất Sài Gòn, bia craft hơn 20 loại tự sản xuất, không gian công nghiệp 2 tầng. Điểm tụ tập của cộng đồng craft beer Việt Nam.","tags":["Quán bia","craft beer","brewery"],"hours":"15:00 - 00:00","priceRange":3,"lat":10.7783,"lng":106.6996},
    {"name":"Pasteur Street Brewing Tap Room","category":"bar","district":"Quận 1","address":"144/3 Pasteur, Bến Nghé, Quận 1, TP.HCM","description":"Brewery tiên phong craft beer Việt Nam mở 2014, bia ủ với nguyên liệu bản địa như jasmine, passion fruit. Tap room nhỏ trong hẻm Pasteur, ăn kèm món Mỹ.","tags":["Quán bia","craft beer","Vietnamese ingredients"],"hours":"11:00 - 23:00","priceRange":3,"lat":10.7773,"lng":106.7009},
    {"name":"Snuffbox","category":"bar","district":"Quận 1","address":"Cao Bá Quát, Bến Nghé, Quận 1, TP.HCM","description":"Hidden cocktail bar phong cách prohibition những năm 1920, vào qua tiệm bán đồng hồ giả. Cocktail menu phân theo nốt hương, ánh đèn mờ sang trọng.","tags":["Quán bar cocktail","speakeasy","prohibition"],"hours":"19:00 - 01:00","priceRange":4,"lat":10.7782,"lng":106.7032},
    {"name":"Firkin Bar","category":"bar","district":"Quận 1","address":"5/4 Nguyễn Siêu, Bến Nghé, Quận 1, TP.HCM","description":"Whisky bar danh tiếng với hơn 400 loại whisky từ khắp thế giới, không khí ấm cúng đậm chất Anh quốc. Điểm hẹn của dân sành whisky Sài Gòn.","tags":["Quán bar","whisky","Asia 50 best"],"hours":"18:00 - 01:00","priceRange":4,"lat":10.7780,"lng":106.7037},
    {"name":"Rogue Saigon","category":"bar","district":"Quận 1","address":"40 Mạc Thị Bưởi, Bến Nghé, Quận 1, TP.HCM","description":"Cocktail bar tinh nghịch giữa con phố ăn chơi Mạc Thị Bưởi, signature menu cocktail Á - Âu pha trộn. Sân thượng nhỏ ngắm phố đêm Quận 1.","tags":["Quán bar cocktail","rooftop nhỏ","craft"],"hours":"18:00 - 02:00","priceRange":3,"lat":10.7762,"lng":106.7045},
    {"name":"Carmen Bar","category":"bar","district":"Quận 1","address":"8 Lý Tự Trọng, Bến Nghé, Quận 1, TP.HCM","description":"Live music bar nổi tiếng với ban nhạc Flamenco và Latin biểu diễn mỗi đêm, không gian Tây Ban Nha rực rỡ. Điểm hẹn của dân nhảy salsa Sài Gòn.","tags":["Quán bar ca nhạc trực tiếp","Latin","flamenco"],"hours":"19:00 - 01:00","priceRange":3,"lat":10.7775,"lng":106.7037},
    {"name":"Acoustic Bar","category":"bar","district":"Quận 3","address":"6E1 Ngô Thời Nhiệm, Phường 7, Quận 3, TP.HCM","description":"Bar acoustic lâu đời nhất Sài Gòn, mở từ 1995 với những đêm nhạc V-pop, Trịnh, rock acoustic. Sân khấu nhỏ, đông kín mọi đêm cuối tuần.","tags":["Quán bar ca nhạc trực tiếp","acoustic","lâu đời"],"hours":"19:00 - 00:30","priceRange":2,"lat":10.7818,"lng":106.6884},
    {"name":"Yoko Bar","category":"bar","district":"Quận 3","address":"22A Nguyễn Thị Diệu, Phường 6, Quận 3, TP.HCM","description":"Bar nhạc sống chuyên indie và rock Việt, sân khấu mở cho ban nhạc trẻ. Không gian retro, bia tươi giá bình dân — điểm hẹn của giới underground.","tags":["Quán bar ca nhạc trực tiếp","indie","underground"],"hours":"19:30 - 01:00","priceRange":2,"lat":10.7795,"lng":106.6925},
    {"name":"Lush Saigon","category":"bar","district":"Quận 1","address":"2 Lý Tự Trọng, Bến Nghé, Quận 1, TP.HCM","description":"Nightclub đẳng cấp ngay góc Lý Tự Trọng - Đồng Khởi, EDM và hip-hop, DJ quốc tế mỗi cuối tuần. Một trong những club đông nhất Sài Gòn.","tags":["Hộp đêm","EDM","DJ"],"hours":"22:00 - 04:00","priceRange":4,"lat":10.7771,"lng":106.7032},
    {"name":"The Observatory","category":"bar","district":"Quận 1","address":"5 Nguyễn Tất Thành, Phường 12, Quận 4, TP.HCM","description":"Club underground ven sông Sài Gòn nổi tiếng với electronic music thử nghiệm, sound system tốt nhất thành phố. Lineup DJ techno và house quốc tế.","tags":["Hộp đêm","techno","underground"],"hours":"22:00 - 05:00","priceRange":3,"lat":10.7660,"lng":106.7066},
    {"name":"Saigon Outcast","category":"bar","district":"TP. Thủ Đức","address":"188/1 Nguyễn Văn Hưởng, Thảo Điền, TP. Thủ Đức, TP.HCM","description":"Sân chơi văn hóa underground tại Thảo Điền với leo núi nhân tạo, skate ramp, đêm nhạc indie và food truck. Khu Tây Thảo Điền tụ tập mỗi cuối tuần.","tags":["Quán bar","cultural","outdoor"],"hours":"17:00 - 01:00","priceRange":2,"lat":10.8044,"lng":106.7320},
    {"name":"Republic Coffee Bar Thảo Điền","category":"bar","district":"TP. Thủ Đức","address":"4 Thảo Điền, TP. Thủ Đức, TP.HCM","description":"Bar - cafe của expat Thảo Điền, ban ngày cà phê, ban đêm cocktail. View thung lũng cây xanh và sông Sài Gòn từ sân thượng.","tags":["Quán bar","Quán cà phê","expat","Thảo Điền"],"hours":"08:00 - 00:00","priceRange":3,"lat":10.8038,"lng":106.7305},
    {"name":"BiaCraft Artisan Ales","category":"bar","district":"Quận 2 / Thảo Điền","address":"90 Xuân Thủy, Thảo Điền, TP. Thủ Đức, TP.HCM","description":"Tap house Việt Nam đầu tiên với 60+ vòi craft beer trong nước và quốc tế. Không gian 2 tầng mát mẻ, bàn dài rộng rãi, có cả pizza và burger.","tags":["Quán bia","craft beer","tap house"],"hours":"15:00 - 00:00","priceRange":3,"lat":10.8055,"lng":106.7332},
    {"name":"Atmos Beer Project","category":"bar","district":"Quận 1","address":"5 Đồng Khởi, Bến Nghé, Quận 1, TP.HCM","description":"Brewery thủ công Việt Nam ngay phố Đồng Khởi, bia ủ tại chỗ với men Bỉ và Đức. Phục vụ kèm món Pháp - Bỉ phù hợp với bia tươi.","tags":["Quán bia","craft beer","brewery"],"hours":"11:00 - 23:00","priceRange":3,"lat":10.7757,"lng":106.7041},
    {"name":"Apocalypse Now Saigon","category":"bar","district":"Quận 1","address":"2C Thi Sách, Bến Nghé, Quận 1, TP.HCM","description":"Hộp đêm huyền thoại Sài Gòn từ 1991, biểu tượng nightlife Việt Nam. Sàn nhảy hai tầng, sân thượng, mở đến sáng — điểm tới của du khách backpacker.","tags":["Hộp đêm","Quán bar","huyền thoại"],"hours":"19:00 - 04:00","priceRange":3,"lat":10.7798,"lng":106.7053},
    {"name":"Bùi Viện Walking Street","category":"bar","district":"Quận 1","address":"Bùi Viện, Phạm Ngũ Lão, Quận 1, TP.HCM","description":"Phố Tây sôi động nhất Sài Gòn với hàng trăm bar, club, beer club mở cửa đến sáng. Cuối tuần đường cấm xe, biến thành phố đi bộ ăn nhậu náo nhiệt.","tags":["phố đi bộ","Quán bar","về đêm","backpacker"],"hours":"17:00 - 04:00","priceRange":2,"lat":10.7676,"lng":106.6929},
    // — HOMESTAY (5) —
    {"name":"The Common Room Project","category":"homestay","district":"Quận 1","address":"6 Hồ Huấn Nghiệp, Bến Nghé, Quận 1, TP.HCM","description":"Boutique homestay phong cách industrial giữa Quận 1, cafe-coworking tầng trệt và 4 phòng nghỉ tầng trên. View Nhà hát Thành phố và phố đi bộ Nguyễn Huệ.","tags":["Homestay","boutique","industrial","cafe"],"hours":"24/7","priceRange":3,"lat":10.7766,"lng":106.7048},
    {"name":"The Hideout Saigon","category":"homestay","district":"Quận 3","address":"281/26/14 Lê Văn Sỹ, Phường 1, Quận 3, TP.HCM","description":"Homestay giấu trong hẻm Lê Văn Sỹ, không gian nhà phố Sài Gòn xưa với gạch bông và đồ gỗ. Chủ nhà thân thiện hướng dẫn ăn uống địa phương.","tags":["Homestay","local","retro"],"hours":"24/7","priceRange":2,"lat":10.7878,"lng":106.6802},
    {"name":"Mango Bay Boutique House","category":"homestay","district":"Quận 1","address":"4 Cô Bắc, Cô Giang, Quận 1, TP.HCM","description":"Nhà ống Sài Gòn cải tạo thành 6 phòng nghỉ phong cách tropical, sân thượng có hồ bơi nhỏ và cây xanh. Gần phố Tây Bùi Viện và chợ Bến Thành.","tags":["Homestay","tropical","rooftop pool"],"hours":"24/7","priceRange":3,"lat":10.7665,"lng":106.6952},
    {"name":"Saigon Backpackers Hostel","category":"homestay","district":"Quận 1","address":"40/31 Bùi Viện, Phạm Ngũ Lão, Quận 1, TP.HCM","description":"Hostel backpacker quốc tế nổi tiếng nhất Bùi Viện, không gian chung sôi động với bar tầng trệt. Phòng dorm và đôi giá mềm, tour Mekong khởi hành mỗi sáng.","tags":["Homestay","backpacker","social"],"hours":"24/7","priceRange":1,"lat":10.7677,"lng":106.6927},
    {"name":"Lavender House Saigon","category":"homestay","district":"Quận 3","address":"32/13 Trần Quang Diệu, Phường 14, Quận 3, TP.HCM","description":"Villa Pháp cổ Q3 cải tạo thành homestay 8 phòng, vườn nhỏ và bể bơi. Phong cách thuộc địa pha hiện đại, gần Tân Định và Nhà thờ Tân Định.","tags":["Homestay","villa","French colonial"],"hours":"24/7","priceRange":3,"lat":10.7898,"lng":106.6764},
  ],

  "da-nang": [
    // — CAFE (20) —
    {"name":"43 Factory Coffee Roaster","category":"cafe","district":"Ngũ Hành Sơn","address":"422 Ngô Thì Sĩ, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Specialty coffee roastery hàng đầu Đà Nẵng, hạt cà phê single-origin rang tại chỗ phục vụ bằng máy espresso La Marzocco. Không gian công nghiệp 2 tầng đẹp như studio.","tags":["specialty coffee","Quán cà phê","roastery","check-in"],"hours":"07:00 - 22:00","priceRange":3,"lat":16.0411,"lng":108.2473},
    {"name":"The Espresso Station","category":"cafe","district":"Hải Châu","address":"99 Trần Phú, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Specialty cafe sang trọng cạnh Bảo tàng Chăm, máy pha và barista cấp quốc gia. Hạt single origin Việt Nam và Ethiopia, bánh ngọt theo mùa.","tags":["Quán cà phê","specialty coffee","barista"],"hours":"07:00 - 22:00","priceRange":3,"lat":16.0604,"lng":108.2236},
    {"name":"Cộng Cà Phê Bạch Đằng","category":"cafe","district":"Hải Châu","address":"96-98 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Chuỗi Cộng Cà Phê view sông Hàn, không gian retro bao cấp đặc trưng. Cà phê cốt dừa huyền thoại và view cầu Rồng - cầu Sông Hàn đẹp nhất bờ tây.","tags":["Quán cà phê","cốt dừa","view sông Hàn","retro"],"hours":"07:00 - 23:30","priceRange":2,"lat":16.0712,"lng":108.2249},
    {"name":"The Local Beans Coffee Roaster","category":"cafe","district":"Hải Châu","address":"171 Trần Phú, P. Phước Ninh, Q. Hải Châu, Đà Nẵng","description":"Cafe rang xay Việt nổi tiếng phố Trần Phú, hạt cà phê từ nông trại Cầu Đất và Buôn Mê Thuột. Không gian đơn giản, dân sành cà phê chuộng.","tags":["Quán cà phê","specialty coffee","roastery"],"hours":"07:00 - 22:00","priceRange":2,"lat":16.0631,"lng":108.2238},
    {"name":"Trill Rooftop Cafe","category":"cafe","district":"Hải Châu","address":"19 Lý Tự Trọng, P. Thạch Thang, Q. Hải Châu, Đà Nẵng","description":"Cafe sân thượng tầng 22 nhìn toàn cảnh thành phố và sông Hàn, đặc biệt đẹp lúc hoàng hôn và buổi tối khi cầu Rồng phun lửa. View 360 hot nhất Đà Nẵng.","tags":["Quán cà phê","bar","view sông Hàn","hoàng hôn"],"hours":"08:00 - 23:30","priceRange":3,"lat":16.0762,"lng":108.2233},
    {"name":"Cafe View Sông Hàn Memory Lounge","category":"cafe","district":"Hải Châu","address":"7 Bạch Đằng, P. Thạch Thang, Q. Hải Châu, Đà Nẵng","description":"Cafe ven sông Hàn cạnh cầu Rồng, không gian ngoài trời rộng và máy lạnh trong nhà. Điểm xem cầu Rồng phun lửa lý tưởng cuối tuần.","tags":["Quán cà phê","view sông Hàn","phun lửa"],"hours":"06:30 - 23:00","priceRange":2,"lat":16.0723,"lng":108.2243},
    {"name":"The Coffee House Bạch Đằng","category":"cafe","district":"Hải Châu","address":"68 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Chuỗi The Coffee House view sông Hàn 2 tầng, không gian rộng và wifi mạnh. Điểm làm việc và gặp gỡ phổ biến của giới văn phòng Đà Nẵng.","tags":["Quán cà phê","chain","wifi","làm việc"],"hours":"07:00 - 22:30","priceRange":2,"lat":16.0708,"lng":108.2246},
    {"name":"Highlands Coffee Indochina Riverside","category":"cafe","district":"Hải Châu","address":"74 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Highlands Coffee tầng 2 view trực diện Cầu Rồng, vị trí prime ngắm phun lửa cuối tuần. Menu Việt - quốc tế, view chính diện cầu đẹp nhất Bạch Đằng.","tags":["Quán cà phê","chain","view Cầu Rồng"],"hours":"06:30 - 23:00","priceRange":2,"lat":16.0717,"lng":108.2247},
    {"name":"Cafe Long Coffee","category":"cafe","district":"Hải Châu","address":"123 Lê Lợi, P. Thạch Thang, Q. Hải Châu, Đà Nẵng","description":"Cafe cổ vintage giữa lòng Đà Nẵng, gạch bông và đồ gỗ những năm 60. Cà phê phin truyền thống và bánh mì pâté kiểu Đà Nẵng cũ.","tags":["Quán cà phê","vintage","cà phê phin"],"hours":"06:00 - 22:00","priceRange":1,"lat":16.0734,"lng":108.2167},
    {"name":"Coco Cafe Đà Nẵng","category":"cafe","district":"Sơn Trà","address":"Lô 12 Võ Nguyên Giáp, P. Mân Thái, Q. Sơn Trà, Đà Nẵng","description":"Cafe view biển Mỹ Khê ngay đường ven biển Võ Nguyên Giáp, không gian mở hướng biển. Đón bình minh và cà phê dừa nhâm nhi gió biển.","tags":["Quán cà phê","view biển","bình minh"],"hours":"05:30 - 22:30","priceRange":2,"lat":16.0805,"lng":108.2462},
    {"name":"Phin Cafe Đà Nẵng","category":"cafe","district":"Sơn Trà","address":"31 Lê Hữu Trác, P. An Hải Bắc, Q. Sơn Trà, Đà Nẵng","description":"Cafe Việt phong cách hoài cổ trong khu An Thượng (Tây ba lô), cà phê phin truyền thống pha bằng nước nóng tự nấu. Quán địa phương dân Tây ưa thích.","tags":["Quán cà phê","cà phê phin","An Thượng","local"],"hours":"06:30 - 22:00","priceRange":1,"lat":16.0566,"lng":108.2415},
    {"name":"XQ Cafe Đà Nẵng","category":"cafe","district":"Hải Châu","address":"43 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Cafe nghệ thuật kết hợp showroom tranh thêu XQ Sử Quán, không gian Á Đông đầy tranh thêu hai mặt. View sông Hàn và nghệ thuật truyền thống Việt.","tags":["Quán cà phê","art","tranh thêu","view sông Hàn"],"hours":"07:30 - 22:30","priceRange":2,"lat":16.0703,"lng":108.2247},
    {"name":"Sun Cafe Bãi Biển","category":"cafe","district":"Sơn Trà","address":"Lô 1 Võ Nguyên Giáp, P. Phước Mỹ, Q. Sơn Trà, Đà Nẵng","description":"Beach cafe trên cát biển Mỹ Khê, ghế lười và dù che dọc bờ biển. Cocktail trái cây và đồ ăn nhẹ, điểm chill cả ngày của dân du lịch.","tags":["Quán cà phê","beach cafe","view biển","chill"],"hours":"07:00 - 23:00","priceRange":2,"lat":16.0682,"lng":108.2466},
    {"name":"Cafe Cộng Mỹ Khê","category":"cafe","district":"Sơn Trà","address":"118 Võ Nguyên Giáp, P. Phước Mỹ, Q. Sơn Trà, Đà Nẵng","description":"Cộng Cà Phê chi nhánh đường ven biển, ban công view bãi tắm Mỹ Khê. Phong cách bao cấp đặc trưng pha với gió biển miền Trung.","tags":["Quán cà phê","chain","view biển","retro"],"hours":"07:00 - 23:00","priceRange":2,"lat":16.0656,"lng":108.2476},
    {"name":"6 Degrees Cafe","category":"cafe","district":"Sơn Trà","address":"112 An Thượng 4, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Cafe & bistro trong khu An Thượng phố Tây, không gian xanh mát với cây cảnh. Brunch quốc tế, cà phê specialty và bánh ngọt tự làm.","tags":["Quán cà phê","brunch","An Thượng","specialty coffee"],"hours":"07:00 - 22:00","priceRange":3,"lat":16.0429,"lng":108.2451},
    {"name":"Roots Plant-based Cafe","category":"cafe","district":"Ngũ Hành Sơn","address":"Mỹ Đa Tây 3, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Cafe healthy vegan đầu tiên Đà Nẵng, smoothie bowl và menu plant-based. Không gian tropical xanh mát, được dân yoga và du khách healthy yêu thích.","tags":["Quán cà phê","vegan","healthy","plant-based"],"hours":"07:30 - 21:30","priceRange":3,"lat":16.0432,"lng":108.2448},
    {"name":"Cafe Đỗ Quyên","category":"cafe","district":"Hải Châu","address":"108 Lê Đình Dương, P. Hải Châu 2, Q. Hải Châu, Đà Nẵng","description":"Cafe sân vườn lâu năm với hồ cá Koi và cây bonsai, không gian nhẹ nhàng thư giãn giữa trung tâm. Phong cách Nhật Bản giữa lòng Đà Nẵng.","tags":["Quán cà phê","sân vườn","Nhật","hồ cá Koi"],"hours":"06:30 - 22:00","priceRange":2,"lat":16.0640,"lng":108.2195},
    {"name":"Cafe Sông Hàn","category":"cafe","district":"Hải Châu","address":"15 Bạch Đằng, P. Thạch Thang, Q. Hải Châu, Đà Nẵng","description":"Cafe view trực diện cầu Sông Hàn quay 0h00, sân thượng và tầng trệt rộng rãi. Điểm xem cầu quay vào nửa đêm cuối tuần lý tưởng.","tags":["Quán cà phê","view sông Hàn","cầu quay"],"hours":"06:30 - 00:30","priceRange":2,"lat":16.0743,"lng":108.2236},
    {"name":"Family Garden Cafe","category":"cafe","district":"Cẩm Lệ","address":"180 Cách Mạng Tháng 8, P. Hòa Thọ Đông, Q. Cẩm Lệ, Đà Nẵng","description":"Cafe sân vườn 3000m² với hồ koi, vườn hoa và khu vui chơi trẻ em. Điểm cuối tuần lý tưởng cho gia đình, menu cà phê và đồ ăn vặt Việt.","tags":["Quán cà phê","sân vườn","gia đình"],"hours":"06:30 - 22:30","priceRange":2,"lat":16.0249,"lng":108.2099},
    {"name":"DalaT Cafe Đà Nẵng","category":"cafe","district":"Hải Châu","address":"45 Quang Trung, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Cafe phong cách Đà Lạt giữa Đà Nẵng, gỗ thông và hoa cẩm tú cầu, máy lạnh mô phỏng khí hậu cao nguyên. Cà phê arabica Cầu Đất và bánh ngọt Đà Lạt.","tags":["Quán cà phê","Đà Lạt","cẩm tú cầu","arabica"],"hours":"07:00 - 22:30","priceRange":2,"lat":16.0712,"lng":108.2196},
    // — HOMESTAY (5) —
    {"name":"Trú Homestay Đà Nẵng","category":"homestay","district":"Sơn Trà","address":"5 An Thượng 2, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Boutique homestay khu An Thượng đi bộ ra biển 200m, 8 phòng phong cách industrial. Sân thượng nhìn biển Mỹ Khê và cafe nhỏ tầng trệt.","tags":["Homestay","boutique","An Thượng","gần biển"],"hours":"24/7","priceRange":3,"lat":16.0428,"lng":108.2455},
    {"name":"Memory Hostel Đà Nẵng","category":"homestay","district":"Hải Châu","address":"39 Trần Quốc Toản, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Hostel backpacker giữa trung tâm Hải Châu, sân thượng quán bar nhìn cầu Rồng. Phòng dorm và đôi, tour Cù Lao Chàm khởi hành tại quầy lễ tân.","tags":["Homestay","backpacker","rooftop bar","Cầu Rồng"],"hours":"24/7","priceRange":1,"lat":16.0681,"lng":108.2218},
    {"name":"Tabalo Hostel Đà Nẵng","category":"homestay","district":"Hải Châu","address":"4 Lê Đình Dương, P. Hải Châu 2, Q. Hải Châu, Đà Nẵng","description":"Hostel boutique 4 sao mini với hồ bơi tầng thượng, sân chơi backpacker quốc tế. 5 phút bộ tới Cầu Rồng và sông Hàn, có tour Bà Nà tại quầy.","tags":["Homestay","hostel","rooftop pool","backpacker"],"hours":"24/7","priceRange":2,"lat":16.0645,"lng":108.2189},
    {"name":"Hi Da Nang Hostel","category":"homestay","district":"Sơn Trà","address":"129 Nguyễn Văn Thoại, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Hostel social cách biển Mỹ Khê 300m, không gian chung sôi động với bia tươi và BBQ tối. Đông backpacker quốc tế, dorm và phòng riêng giá rẻ.","tags":["Homestay","social","BBQ","gần biển"],"hours":"24/7","priceRange":1,"lat":16.0410,"lng":108.2440},
    {"name":"Sea Wind Boutique Homestay","category":"homestay","district":"Sơn Trà","address":"22 Hà Bổng, P. Phước Mỹ, Q. Sơn Trà, Đà Nẵng","description":"Homestay phong cách Địa Trung Hải, ban công nhìn ra biển Mỹ Khê 5 phút bộ. Chủ nhà thân thiện hướng dẫn ăn hải sản và tour Sơn Trà.","tags":["Homestay","boutique","Mediterranean","gần biển"],"hours":"24/7","priceRange":2,"lat":16.0626,"lng":108.2455},
    // — BAR (5) —
    {"name":"7 Bridges Brewing Co.","category":"bar","district":"Hải Châu","address":"95 Nguyễn Văn Linh, P. Nam Dương, Q. Hải Châu, Đà Nẵng","description":"Brewery craft Đà Nẵng đầu tiên, hơn 12 loại bia ủ tại chỗ với men và hops nhập khẩu. Sân thượng và tầng trệt thoáng đãng, ăn kèm pizza và món Mỹ.","tags":["Quán bia","craft beer","brewery"],"hours":"15:00 - 23:30","priceRange":3,"lat":16.0639,"lng":108.2153},
    {"name":"East West Brewing Đà Nẵng","category":"bar","district":"Hải Châu","address":"34 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Chi nhánh Đà Nẵng của brewery nổi tiếng Sài Gòn, view sông Hàn 3 tầng. Bia ủ tại chỗ kết hợp menu Á - Âu fusion, sân thượng ngắm cầu Rồng phun lửa.","tags":["Quán bia","craft beer","view sông Hàn","bar"],"hours":"11:00 - 00:00","priceRange":3,"lat":16.0710,"lng":108.2250},
    {"name":"Waterfront Bar Đà Nẵng","category":"bar","district":"Hải Châu","address":"150-152 Bạch Đằng, P. Phước Ninh, Q. Hải Châu, Đà Nẵng","description":"Bar và bistro châu Âu lâu đời view sông Hàn, đầu bếp Úc và menu cocktail signature. Điểm hẹn của expat và doanh nhân quốc tế Đà Nẵng.","tags":["Quán bar","cocktail","expat","view sông"],"hours":"10:00 - 00:00","priceRange":4,"lat":16.0668,"lng":108.2249},
    {"name":"The Hideout Beer & Bar","category":"bar","district":"Sơn Trà","address":"33 An Thượng 4, P. Mỹ An, Q. Ngũ Hành Sơn, Đà Nẵng","description":"Bar craft beer khu An Thượng, tap house 24 vòi bia Việt - quốc tế. Sân vườn ngoài trời, đông Tây ba lô và dân lướt sóng Mỹ Khê.","tags":["Quán bia","craft beer","An Thượng","tap house"],"hours":"16:00 - 01:00","priceRange":2,"lat":16.0432,"lng":108.2448},
    {"name":"OQ Lounge Pub","category":"bar","district":"Hải Châu","address":"100 Bạch Đằng, P. Hải Châu 1, Q. Hải Châu, Đà Nẵng","description":"Pub kiểu Anh ven sông Hàn với hơn 50 loại bia chai quốc tế, bóng đá Premier League cuối tuần. Sân thượng nhìn cầu Rồng phun lửa.","tags":["Quán bar","pub","bóng đá","view sông Hàn"],"hours":"15:00 - 01:00","priceRange":3,"lat":16.0717,"lng":108.2248},
  ],

  "ha-noi": [
    // — BAR (20) — Tạ Hiện zone + Old Quarter + Tây Hồ
    {"name":"Tạ Hiện Beer Street","category":"bar","district":"Hoàn Kiếm","address":"Tạ Hiện, P. Hàng Buồm, Q. Hoàn Kiếm, Hà Nội","description":"Phố bia Tạ Hiện - giao lộ Lương Ngọc Quyến nổi tiếng nhất phố cổ Hà Nội với hàng trăm ghế nhựa đỏ tràn ra hè. Bia hơi 8k cốc, đông kín từ chiều tới khuya.","tags":["phố đi bộ","Quán bia","bia hơi","phố cổ"],"hours":"15:00 - 00:00","priceRange":1,"lat":21.0341,"lng":105.8517},
    {"name":"Polite & Co.","category":"bar","district":"Hoàn Kiếm","address":"5 Bảo Khánh, P. Hàng Trống, Q. Hoàn Kiếm, Hà Nội","description":"Cocktail bar speakeasy tinh tế trong ngõ nhỏ Bảo Khánh, không gian thư viện Anh quốc cổ điển. Lọt Asia 50 Best Bars - một trong những bar craft hàng đầu Hà Nội.","tags":["Quán bar cocktail","speakeasy","Asia 50 best"],"hours":"18:00 - 01:00","priceRange":4,"lat":21.0306,"lng":105.8499},
    {"name":"Nê Cocktail Bar","category":"bar","district":"Hoàn Kiếm","address":"3 Tống Duy Tân, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội","description":"Cocktail bar signature của bartender Pham Tien Tiep, signature cocktail Phở nổi tiếng quốc tế. Không gian nhỏ phong cách Á Đông, lọt nhiều bảng xếp hạng quốc tế.","tags":["Quán bar cocktail","signature","cocktail Phở"],"hours":"19:00 - 01:00","priceRange":4,"lat":21.0310,"lng":105.8431},
    {"name":"Unicorn Pub","category":"bar","district":"Hoàn Kiếm","address":"2A Đào Duy Từ, P. Hàng Buồm, Q. Hoàn Kiếm, Hà Nội","description":"Pub backpacker đông nhất Tạ Hiện zone với DJ EDM, bia tươi và shot rẻ. Đông Tây ba lô và dân Hà Nội đi chơi phố cổ cuối tuần.","tags":["Quán bar","backpacker","EDM","phố cổ"],"hours":"17:00 - 03:00","priceRange":2,"lat":21.0340,"lng":105.8518},
    {"name":"Hair of the Dog","category":"bar","district":"Hoàn Kiếm","address":"2 Tạ Hiện, P. Hàng Buồm, Q. Hoàn Kiếm, Hà Nội","description":"Quán bar kiểu Tây ngay ngã ba Tạ Hiện - Lương Ngọc Quyến, bia chai và craft, đông expat. Live music vào cuối tuần, sân thượng nhỏ ngắm phố cổ.","tags":["Quán bar","expat","Tạ Hiện","live music"],"hours":"18:00 - 02:00","priceRange":2,"lat":21.0342,"lng":105.8517},
    {"name":"The Roof Top Bar Bia Hơi","category":"bar","district":"Hoàn Kiếm","address":"5 Đinh Liệt, P. Hàng Bạc, Q. Hoàn Kiếm, Hà Nội","description":"Bar sân thượng cao nhất khu phố cổ, view nóc nhà phố cổ Hà Nội. Bia hơi và cocktail giá mềm, hoàng hôn check-in trên nóc đẹp.","tags":["Quán bar","bar","view phố cổ","bia hơi"],"hours":"16:00 - 00:00","priceRange":2,"lat":21.0334,"lng":105.8511},
    {"name":"Skyline Hanoi Rooftop","category":"bar","district":"Hoàn Kiếm","address":"38 Gia Ngư, P. Hàng Bạc, Q. Hoàn Kiếm, Hà Nội","description":"Rooftop bar tầng 21 view 360° Hồ Gươm và phố cổ, signature cocktail và menu Á Âu. Một trong những bar trên cao đẹp nhất Hà Nội.","tags":["Quán bar","bar","view Hồ Gươm","cocktail"],"hours":"17:00 - 01:00","priceRange":4,"lat":21.0319,"lng":105.8515},
    {"name":"Top of Hanoi","category":"bar","district":"Cầu Giấy","address":"Tầng 65 Lotte Center, 54 Liễu Giai, P. Cống Vị, Q. Ba Đình, Hà Nội","description":"Rooftop bar trên tầng 65 Lotte Center cao nhất Hà Nội, view 360° toàn thành phố. Cocktail signature, đặc biệt đẹp lúc hoàng hôn và đèn đêm bật.","tags":["Quán bar","bar","tầng cao nhất","view 360"],"hours":"17:00 - 00:00","priceRange":4,"lat":21.0334,"lng":105.8120},
    {"name":"Twilight Sky Bar","category":"bar","district":"Hoàn Kiếm","address":"Tầng 16 Hilton Opera, 1 Lê Thánh Tông, Q. Hoàn Kiếm, Hà Nội","description":"Sky bar Hilton Opera tầng 16 view Nhà hát Lớn và Bảo tàng Lịch sử, không gian sang trọng. Cocktail và canapés cho khách doanh nhân và du lịch cao cấp.","tags":["Quán bar","bar","Hilton","sang trọng"],"hours":"17:00 - 01:00","priceRange":4,"lat":21.0246,"lng":105.8580},
    {"name":"Summit Lounge Pan Pacific","category":"bar","district":"Tây Hồ","address":"Tầng 20 Pan Pacific, 1 Thanh Niên, Q. Ba Đình, Hà Nội","description":"Bar tầng 20 khách sạn Pan Pacific bên hồ Tây, view hồ Tây và hồ Trúc Bạch 270°. Cocktail signature và sushi-bar Nhật trong không khí sang trọng.","tags":["Quán bar","bar","Hồ Tây","sang trọng"],"hours":"17:00 - 00:00","priceRange":4,"lat":21.0497,"lng":105.8417},
    {"name":"Standing Bar","category":"bar","district":"Hai Bà Trưng","address":"170 Trần Vũ, P. Trúc Bạch, Q. Ba Đình, Hà Nội","description":"Craft beer bar bên hồ Trúc Bạch chuyên bia thủ công Việt Nam, hơn 30 vòi bia Pasteur Street, Heart of Darkness. Sân thượng view hồ và menu món nhậu.","tags":["Quán bia","craft beer","Hồ Trúc Bạch","tap house"],"hours":"15:00 - 00:00","priceRange":2,"lat":21.0445,"lng":105.8419},
    {"name":"Pasteur Street Brewing Hà Nội","category":"bar","district":"Hoàn Kiếm","address":"1 Ấu Triệu, P. Hàng Trống, Q. Hoàn Kiếm, Hà Nội","description":"Chi nhánh Hà Nội của brewery craft beer Việt Nam nổi tiếng, ngay cạnh Nhà thờ Lớn. Bia Jasmine IPA và Passion Fruit Wheat ăn kèm pizza Mỹ.","tags":["Quán bia","craft beer","Nhà thờ Lớn"],"hours":"11:00 - 00:00","priceRange":3,"lat":21.0288,"lng":105.8493},
    {"name":"Beer Plaza Hà Nội","category":"bar","district":"Hoàn Kiếm","address":"95 Lương Ngọc Quyến, P. Hàng Buồm, Q. Hoàn Kiếm, Hà Nội","description":"Tap house craft beer trên phố Lương Ngọc Quyến với hơn 20 vòi bia Việt - quốc tế. Không gian 2 tầng và sân thượng nhỏ, đông cuối tuần.","tags":["Quán bia","craft beer","Tạ Hiện","tap house"],"hours":"16:00 - 01:00","priceRange":2,"lat":21.0341,"lng":105.8511},
    {"name":"Le Pub Hanoi","category":"bar","district":"Hoàn Kiếm","address":"25 Hàng Bè, P. Hàng Bạc, Q. Hoàn Kiếm, Hà Nội","description":"Pub kiểu Anh - Pháp giữa phố cổ với hơn 80 loại bia chai từ Bỉ, Đức, Mỹ. Bóng đá quốc tế tất cả các giải lớn, sân thượng nhỏ.","tags":["Quán bar","pub","bóng đá","craft beer"],"hours":"10:00 - 01:00","priceRange":3,"lat":21.0334,"lng":105.8517},
    {"name":"Tadioto","category":"bar","district":"Hoàn Kiếm","address":"24B Tống Duy Tân, P. Hàng Bông, Q. Hoàn Kiếm, Hà Nội","description":"Bar nghệ thuật của nhà văn Nguyễn Quí Đức, không gian phòng khách Hà Nội xưa với sách và tranh. Sân khấu thơ và jazz acoustic vào cuối tuần.","tags":["Quán bar","art","jazz","văn nghệ"],"hours":"18:00 - 01:00","priceRange":3,"lat":21.0307,"lng":105.8428},
    {"name":"Binh Minh Jazz Club","category":"bar","district":"Hoàn Kiếm","address":"1A Tràng Tiền, P. Tràng Tiền, Q. Hoàn Kiếm, Hà Nội","description":"Câu lạc bộ jazz lâu đời của nghệ sĩ Quyền Văn Minh, biểu diễn jazz sống mỗi đêm. Không gian nhỏ ấm cúng, điểm tới của dân yêu nhạc Hà Nội.","tags":["Quán bar ca nhạc trực tiếp","jazz","lâu đời"],"hours":"19:00 - 00:00","priceRange":3,"lat":21.0250,"lng":105.8568},
    {"name":"Savage Hà Nội","category":"bar","district":"Hai Bà Trưng","address":"112 Triệu Việt Vương, P. Bùi Thị Xuân, Q. Hai Bà Trưng, Hà Nội","description":"Club underground chuyên electronic music và techno, sound system tốt nhất Hà Nội. Lineup DJ quốc tế hằng tháng, mở đến sáng cuối tuần.","tags":["Hộp đêm","techno","underground","electronic"],"hours":"22:00 - 04:00","priceRange":3,"lat":21.0125,"lng":105.8505},
    {"name":"GenZ Cocktail Bar","category":"bar","district":"Hoàn Kiếm","address":"15A Phan Bội Châu, P. Cửa Nam, Q. Hoàn Kiếm, Hà Nội","description":"Cocktail bar trẻ trung phong cách neon, signature cocktail và mocktail Việt. Đông giới trẻ Hà Nội, nhạc EDM và pop chill.","tags":["Quán bar cocktail","neon","Gen Z","EDM"],"hours":"18:00 - 02:00","priceRange":2,"lat":21.0263,"lng":105.8455},
    {"name":"The Bar at Capella Hanoi","category":"bar","district":"Hoàn Kiếm","address":"Capella Hanoi, 11 Lê Phụng Hiểu, P. Tràng Tiền, Q. Hoàn Kiếm, Hà Nội","description":"Bar sang trọng nhất Hà Nội tại Capella, design phong cách opera đầu thế kỷ 20. Cocktail signature đoạt giải quốc tế, dress code smart casual.","tags":["Quán bar","luxury","Capella","sang trọng"],"hours":"17:00 - 01:00","priceRange":4,"lat":21.0271,"lng":105.8569},
    {"name":"Beer Garden 198 Tây Sơn","category":"bar","district":"Đống Đa","address":"198 Tây Sơn, P. Quang Trung, Q. Đống Đa, Hà Nội","description":"Vườn bia ngoài trời rộng nhất Đống Đa, hàng trăm ghế sân vườn và sân khấu nhạc sống. Bia hơi và đồ nhậu Việt giá mềm, đông gia đình và bạn bè.","tags":["Quán bia sân vườn","bia hơi","outdoor","gia đình"],"hours":"15:00 - 23:30","priceRange":1,"lat":21.0096,"lng":105.8253},
    // — HOMESTAY (5) —
    {"name":"Hanoi Old Quarter Homestay","category":"homestay","district":"Hoàn Kiếm","address":"45 Hàng Bè, P. Hàng Bạc, Q. Hoàn Kiếm, Hà Nội","description":"Nhà ống phố cổ 4 tầng cải tạo thành homestay 6 phòng, gạch hoa và đồ gỗ cổ. Sân thượng nhìn nóc nhà phố cổ và cách Hồ Gươm 100m.","tags":["Homestay","phố cổ","nhà ống","Hồ Gươm"],"hours":"24/7","priceRange":2,"lat":21.0335,"lng":105.8518},
    {"name":"Tomodachi House Hanoi","category":"homestay","district":"Tây Hồ","address":"11 Đặng Thai Mai, P. Quảng An, Q. Tây Hồ, Hà Nội","description":"Boutique homestay Nhật Bản bên hồ Tây, 8 phòng phong cách ryokan với tatami. Vườn Nhật và onsen nhỏ, chủ nhà người Nhật biết tiếng Việt.","tags":["Homestay","Nhật Bản","Hồ Tây","ryokan"],"hours":"24/7","priceRange":3,"lat":21.0617,"lng":105.8264},
    {"name":"Little Hanoi Hostel","category":"homestay","district":"Hoàn Kiếm","address":"32 Hàng Tre, P. Hàng Bạc, Q. Hoàn Kiếm, Hà Nội","description":"Hostel backpacker giữa phố cổ, dorm và phòng riêng giá mềm. Tour Hạ Long và Sa Pa khởi hành tại quầy, bar tầng trệt đông Tây ba lô mỗi tối.","tags":["Homestay","backpacker","phố cổ","hostel"],"hours":"24/7","priceRange":1,"lat":21.0336,"lng":105.8527},
    {"name":"Maison de Tét Decor","category":"homestay","district":"Tây Hồ","address":"Ngõ 4 Tô Ngọc Vân, P. Quảng An, Q. Tây Hồ, Hà Nội","description":"Boutique guesthouse bên hồ Tây phong cách Pháp Đông Dương, vườn cây và hồ koi. 6 phòng nghệ thuật do nghệ sĩ thiết kế, cafe và gallery tầng trệt.","tags":["Homestay","boutique","art","Hồ Tây"],"hours":"24/7","priceRange":4,"lat":21.0631,"lng":105.8262},
    {"name":"Old Quarter View Hostel","category":"homestay","district":"Hoàn Kiếm","address":"22 Hàng Quạt, P. Hàng Gai, Q. Hoàn Kiếm, Hà Nội","description":"Hostel 5 tầng phố cổ Hàng Quạt, sân thượng quán bar nhìn phố cổ và Nhà thờ Lớn. Dorm rẻ và phòng đôi, đông backpacker quốc tế giao lưu.","tags":["Homestay","hostel","rooftop bar","phố cổ"],"hours":"24/7","priceRange":1,"lat":21.0314,"lng":105.8497},
  ],

  "da-lat": [
    // — VIEWPOINT (15) — Đà Lạt's signature category
    {"name":"Đồi chè Tâm Châu","category":"viewpoint","district":"Bảo Lộc / Lâm Đồng","address":"Bảo Lộc, Lâm Đồng (cách Đà Lạt 110km)","description":"Đồi chè bạt ngàn của thương hiệu chè Tâm Châu, khung cảnh xanh mướt trải dài tầng tầng. Điểm dừng chân chụp ảnh trên đường xuôi từ Sài Gòn lên Đà Lạt.","tags":["Điểm thu hút khách du lịch","đồi chè","check-in"],"hours":"07:00 - 17:00","priceRange":1,"lat":11.5395,"lng":107.7973},
    {"name":"Đỉnh núi Bidoup","category":"viewpoint","district":"Lạc Dương","address":"Vườn quốc gia Bidoup - Núi Bà, Lạc Dương, Lâm Đồng","description":"Đỉnh núi cao 2.287m, nóc nhà Tây Nguyên với rừng nguyên sinh và biển mây. Tuyến trekking 2 ngày 1 đêm, đỉnh đẹp ngắm bình minh.","tags":["Điểm thu hút khách du lịch","núi","trekking","săn mây"],"hours":"06:00 - 17:00","priceRange":2,"lat":12.1014,"lng":108.6622},
    {"name":"Tuyệt Tình Cốc Đà Lạt","category":"viewpoint","district":"Phường 7","address":"Phước Thành, Phường 7, TP. Đà Lạt, Lâm Đồng","description":"Hồ nước xanh ngọc giữa vực đá granite, được mệnh danh Tuyệt Tình Cốc của Đà Lạt. Điểm check-in hot Instagram nhưng cần cẩn trọng vực sâu.","tags":["Điểm thu hút khách du lịch","hồ","sống ảo","check-in"],"hours":"06:00 - 18:00","priceRange":1,"lat":11.9923,"lng":108.4742},
    {"name":"Đồi Đa Phú","category":"viewpoint","district":"Phường 7","address":"Đa Phú, Phường 7, TP. Đà Lạt, Lâm Đồng","description":"Đồi thông cao nhìn toàn cảnh hồ Suối Vàng và đồi chè, điểm săn mây buổi sáng và ngắm hoàng hôn lý tưởng. Cắm trại và đốt lửa trại đêm.","tags":["Điểm thu hút khách du lịch","săn mây","cắm trại","đồi thông"],"hours":"24/7","priceRange":1,"lat":12.0083,"lng":108.4067},
    {"name":"Hồ Suối Vàng","category":"viewpoint","district":"Lạc Dương","address":"Suối Vàng, Lạc Dương, Lâm Đồng","description":"Hồ nước nhân tạo lớn giữa rừng thông với cảnh sắc nguyên sơ, cách Đà Lạt 12km. Cắm trại và chèo SUP, điểm dã ngoại cuối tuần của dân Đà Lạt.","tags":["Điểm thu hút khách du lịch","hồ","cắm trại","SUP"],"hours":"24/7","priceRange":1,"lat":12.0044,"lng":108.4022},
    {"name":"Vườn quốc gia Bidoup - Núi Bà","category":"viewpoint","district":"Lạc Dương","address":"Lạc Dương, Lâm Đồng","description":"Vườn quốc gia rộng 70.000ha với hệ sinh thái rừng lá kim quý hiếm và đa dạng thú rừng. Trekking nhiều cấp độ, ngắm hoa đỗ quyên nở tháng 3.","tags":["Điểm thu hút khách du lịch","trekking","rừng nguyên sinh","sinh thái"],"hours":"06:00 - 17:00","priceRange":2,"lat":12.1167,"lng":108.6583},
    {"name":"Thác Pongour","category":"viewpoint","district":"Đức Trọng","address":"Tân Hội, Đức Trọng, Lâm Đồng","description":"Thác nước 7 tầng đẹp nhất Tây Nguyên, dài 100m và cao 40m. Được mệnh danh Nam Thiên Đệ Nhất Thác, lễ hội Pongour vào rằm tháng giêng âm lịch.","tags":["Điểm thu hút khách du lịch","thác","Pongour","check-in"],"hours":"07:00 - 17:00","priceRange":1,"lat":11.7186,"lng":108.3214},
    {"name":"Thác Dambri","category":"viewpoint","district":"Bảo Lộc","address":"Lộc Tân, Bảo Lộc, Lâm Đồng","description":"Thác nước cao nhất Lâm Đồng với độ cao 70m, máng trượt cao tốc và đường mòn xuyên rừng. Khu du lịch sinh thái hoàn chỉnh trên đường Sài Gòn - Đà Lạt.","tags":["Điểm thu hút khách du lịch","thác","máng trượt","sinh thái"],"hours":"07:30 - 17:00","priceRange":2,"lat":11.6075,"lng":107.7019},
    {"name":"Đồi cỏ tuyết Tà Năng","category":"viewpoint","district":"Đức Trọng","address":"Tà Hine, Đức Trọng, Lâm Đồng","description":"Cung trekking Tà Năng - Phan Dũng nổi tiếng nhất Việt Nam, đồi cỏ rộng và view núi rừng ngút ngàn. Trekking 2N1Đ, cắm trại trên đồi cao.","tags":["Điểm thu hút khách du lịch","trekking","cắm trại","đồi cỏ"],"hours":"24/7","priceRange":2,"lat":11.6500,"lng":108.4500},
    {"name":"Quảng trường Lâm Viên","category":"viewpoint","district":"Phường 10","address":"Đường Trần Quốc Toản, Phường 10, TP. Đà Lạt, Lâm Đồng","description":"Quảng trường lớn nhất Đà Lạt bên Hồ Xuân Hương với hai công trình bông atisô và hoa dã quỳ khổng lồ. Điểm tổ chức Festival Hoa và chợ đêm cuối tuần.","tags":["Điểm thu hút khách du lịch","biểu tượng","check-in","Hồ Xuân Hương"],"hours":"24/7","priceRange":1,"lat":11.9426,"lng":108.4434},
    {"name":"Đỉnh Núi Voi","category":"viewpoint","district":"Đức Trọng","address":"Đức Trọng, Lâm Đồng","description":"Đỉnh núi đá hình con voi nằm phục, độ cao 1.754m, có cung trekking ngắm bình minh và hoàng hôn. Cảnh quan núi đá hùng vĩ, đường lên dốc cao.","tags":["Điểm thu hút khách du lịch","núi","trekking","bình minh"],"hours":"05:00 - 18:00","priceRange":1,"lat":11.8278,"lng":108.3956},
    {"name":"Đồi Robin","category":"viewpoint","district":"Phường 3","address":"Đường Trúc Lâm Yên Tử, Phường 3, TP. Đà Lạt, Lâm Đồng","description":"Đồi cao gần Thiền viện Trúc Lâm với cáp treo và đường mòn nhìn toàn cảnh hồ Tuyền Lâm. Điểm cắm trại và đốt lửa trại đêm có view hồ.","tags":["Điểm thu hút khách du lịch","cáp treo","view hồ","cắm trại"],"hours":"07:00 - 17:00","priceRange":2,"lat":11.9028,"lng":108.4422},
    {"name":"Đường hầm đất sét","category":"viewpoint","district":"Phường 4","address":"Tiểu khu 53A, Phường 4, TP. Đà Lạt, Lâm Đồng","description":"Khu du lịch đường hầm đất sét điêu khắc dài 2km bên hồ Tuyền Lâm, tái hiện lịch sử Đà Lạt. Công trình điêu khắc đất sét lớn nhất Việt Nam.","tags":["Điểm thu hút khách du lịch","đường hầm","điêu khắc","check-in"],"hours":"07:30 - 17:30","priceRange":2,"lat":11.9000,"lng":108.4361},
    {"name":"Đồi Thiên Phúc Đức cây cô đơn","category":"viewpoint","district":"Phường 7","address":"Phường 7, TP. Đà Lạt, Lâm Đồng","description":"Đồi cỏ rộng với một cây thông cô đơn trên đỉnh, biểu tượng Instagram Đà Lạt. Hoàng hôn và sương sớm đẹp như tranh, dân chụp ảnh cưới ưa chuộng.","tags":["Điểm thu hút khách du lịch","cây cô đơn","sống ảo","hoàng hôn"],"hours":"24/7","priceRange":1,"lat":11.9889,"lng":108.4744},
    {"name":"Vườn Bích Câu","category":"viewpoint","district":"Phường 8","address":"đường Phù Đổng Thiên Vương, Phường 8, TP. Đà Lạt, Lâm Đồng","description":"Vườn hoa nghệ thuật trên đồi cao gần Thung lũng Tình Yêu với hàng trăm loài hoa châu Âu. Nhà kính lan và vườn hồng, điểm ngắm cảnh và mua hoa.","tags":["Điểm thu hút khách du lịch","vườn hoa","nhà kính","mua hoa"],"hours":"07:00 - 17:30","priceRange":1,"lat":11.9719,"lng":108.4467},
    // — BAR (5) — Đà Lạt has only 1 curated; add a few real ones
    {"name":"Lululola Coffee Đà Lạt","category":"bar","district":"Phường 3","address":"Hẻm 17 Đường Quang Trung, Phường 9, TP. Đà Lạt, Lâm Đồng","description":"Cafe - bar acoustic nổi tiếng Đà Lạt trên đồi thông, đêm acoustic nhạc Trịnh và indie. Sân thượng ngắm rừng thông và sương mù, đèn nến lãng mạn.","tags":["Quán bar ca nhạc trực tiếp","acoustic","đồi thông","Đà Lạt"],"hours":"08:00 - 23:00","priceRange":2,"lat":11.9528,"lng":108.4528},
    {"name":"Là Việt Coffee Bar","category":"bar","district":"Phường 5","address":"200 Nguyễn Công Trứ, Phường 8, TP. Đà Lạt, Lâm Đồng","description":"Cafe - bar specialty coffee chuyên cocktail có cà phê arabica. Sân vườn rộng và rang xay tại chỗ, điểm hẹn của dân yêu cà phê và cocktail.","tags":["Quán bar","Quán cà phê","cocktail","arabica"],"hours":"07:30 - 23:00","priceRange":3,"lat":11.9494,"lng":108.4628},
    {"name":"Memories Bar Đà Lạt","category":"bar","district":"Phường 1","address":"7 Trương Công Định, Phường 1, TP. Đà Lạt, Lâm Đồng","description":"Bar acoustic ấm cúng phố Trương Công Định, ban nhạc sống mỗi đêm và menu cocktail Đà Lạt sương mù. Đông giới trẻ cuối tuần.","tags":["Quán bar","Quán bar ca nhạc trực tiếp","acoustic"],"hours":"18:00 - 01:00","priceRange":2,"lat":11.9395,"lng":108.4382},
    {"name":"Maison Marou Đà Lạt Bar","category":"bar","district":"Phường 1","address":"đường Khe Sanh, Phường 10, TP. Đà Lạt, Lâm Đồng","description":"Chocolate bar - cocktail bar độc đáo của thương hiệu Marou, cocktail có ca cao Việt Nam. Không gian sang trọng giữa rừng thông Đà Lạt.","tags":["Quán bar cocktail","chocolate","Marou","sang trọng"],"hours":"15:00 - 23:00","priceRange":4,"lat":11.9536,"lng":108.4456},
    {"name":"V Bar Đà Lạt","category":"bar","district":"Phường 1","address":"54 Nguyễn Chí Thanh, Phường 1, TP. Đà Lạt, Lâm Đồng","description":"Pub nhạc sống nổi tiếng Đà Lạt với rock cover band mỗi đêm, sân khấu chuyên nghiệp. Đông sinh viên và Tây ba lô vào dịp cuối tuần.","tags":["Quán bar ca nhạc trực tiếp","rock","cover band"],"hours":"19:00 - 01:00","priceRange":2,"lat":11.9387,"lng":108.4344},
  ],

  "ninh-binh": [
    // — VIEWPOINT (12) —
    {"name":"Hang Múa","category":"viewpoint","district":"Hoa Lư","address":"Khê Đầu Hạ, Ninh Xuân, Hoa Lư, Ninh Bình","description":"Đỉnh núi với 500 bậc đá lên ngắm toàn cảnh Tam Cốc, vịnh Hạ Long trên cạn nhìn từ trên cao. Điểm check-in biểu tượng Ninh Bình.","tags":["Điểm thu hút khách du lịch","leo núi","Tam Cốc","check-in"],"hours":"06:00 - 19:00","priceRange":2,"lat":20.2244,"lng":105.9419},
    {"name":"Tam Cốc - Bích Động","category":"viewpoint","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Vịnh Hạ Long trên cạn với 3 hang động xuyên núi đá vôi, đi thuyền nan của người dân chèo bằng chân. Cánh đồng lúa vàng tháng 5-6 đẹp nhất.","tags":["Điểm thu hút khách du lịch","thuyền","hang động","lúa vàng"],"hours":"07:00 - 17:00","priceRange":3,"lat":20.2186,"lng":105.9303},
    {"name":"Vườn quốc gia Cúc Phương","category":"viewpoint","district":"Nho Quan","address":"Cúc Phương, Nho Quan, Ninh Bình","description":"Vườn quốc gia đầu tiên Việt Nam thành lập 1962, rừng nguyên sinh nhiệt đới với cây chò chỉ ngàn năm. Trung tâm cứu hộ linh trưởng và rùa.","tags":["Điểm thu hút khách du lịch","rừng","sinh thái","linh trưởng"],"hours":"06:00 - 18:00","priceRange":2,"lat":20.3500,"lng":105.6000},
    {"name":"Khu Du Lịch Sinh Thái Thung Nham","category":"viewpoint","district":"Hoa Lư","address":"Hang Bụt, Ninh Hải, Hoa Lư, Ninh Bình","description":"Khu sinh thái với vườn chim cò lớn nhất miền Bắc, hàng vạn cò bay về làm tổ chiều tối. Thuyền tham quan hang động và rừng ngập nước.","tags":["Điểm thu hút khách du lịch","vườn chim","sinh thái","thuyền"],"hours":"07:00 - 17:30","priceRange":3,"lat":20.2161,"lng":105.9614},
    {"name":"Đầm Vân Long","category":"viewpoint","district":"Gia Viễn","address":"Gia Vân, Gia Viễn, Ninh Bình","description":"Khu bảo tồn thiên nhiên đất ngập nước lớn nhất đồng bằng sông Hồng, nơi sinh sống của voọc mông trắng quý hiếm. Thuyền nan đi sâu vào đầm yên tĩnh.","tags":["Điểm thu hút khách du lịch","đất ngập nước","voọc","thuyền"],"hours":"07:00 - 17:00","priceRange":2,"lat":20.3372,"lng":105.8722},
    {"name":"Cố đô Hoa Lư","category":"viewpoint","district":"Hoa Lư","address":"Trường Yên, Hoa Lư, Ninh Bình","description":"Kinh đô đầu tiên của nước Đại Cồ Việt thời Đinh - Tiền Lê, di tích lịch sử quốc gia đặc biệt. Đền vua Đinh - vua Lê với kiến trúc cổ kính.","tags":["Điểm thu hút khách du lịch","di tích","kinh đô","lịch sử"],"hours":"07:00 - 18:00","priceRange":2,"lat":20.2811,"lng":105.9111},
    {"name":"Hang Thung Nắng","category":"viewpoint","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Hang động ít người biết trong khu Tam Cốc, đi thuyền nan xuyên hang ngắm rừng ngập nước. Cảnh sắc tĩnh lặng và không đông như Tam Cốc.","tags":["Điểm thu hút khách du lịch","hang động","thuyền","yên tĩnh"],"hours":"07:00 - 17:00","priceRange":2,"lat":20.2236,"lng":105.9356},
    {"name":"Chùa Bích Động","category":"viewpoint","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Cụm chùa cổ xây dựng trên ba tầng núi đá vôi gần Tam Cốc, một trong những ngôi chùa đẹp nhất miền Bắc. Đường leo bộ qua hang Tối lên chùa.","tags":["Điểm thu hút khách du lịch","chùa","leo núi","cổ kính"],"hours":"06:00 - 18:00","priceRange":1,"lat":20.2186,"lng":105.9303},
    {"name":"Động Am Tiên","category":"viewpoint","district":"Hoa Lư","address":"Trường Yên, Hoa Lư, Ninh Bình","description":"Hang động trong lòng núi đá vôi, có hồ nước ngọt trong xanh quanh năm, được gọi là Tuyệt Tình Cốc Ninh Bình. Yên tĩnh và mát mẻ.","tags":["Điểm thu hút khách du lịch","hang động","hồ","Tuyệt Tình Cốc"],"hours":"07:00 - 17:00","priceRange":2,"lat":20.2872,"lng":105.9136},
    {"name":"Thung Lá Tam Cốc","category":"viewpoint","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Thung lũng yên tĩnh giữa núi đá vôi với cánh đồng lúa và làng nhỏ. Ít du khách, đường đi bộ và đạp xe ngắm cảnh nguyên sơ.","tags":["Điểm thu hút khách du lịch","thung lũng","đạp xe","yên tĩnh"],"hours":"24/7","priceRange":1,"lat":20.2222,"lng":105.9333},
    {"name":"Phố cổ Hoa Lư","category":"viewpoint","district":"Hoa Lư","address":"Trường Yên, Hoa Lư, Ninh Bình","description":"Khu phố cổ tái hiện kiến trúc kinh đô Hoa Lư xưa với nhà gỗ, đèn lồng và chợ đêm. Điểm ăn uống và mua sắm tối, lễ hội ánh sáng cuối tuần.","tags":["Điểm thu hút khách du lịch","phố cổ","chợ đêm","check-in"],"hours":"08:00 - 22:30","priceRange":2,"lat":20.2806,"lng":105.9100},
    {"name":"Đỉnh Yên Mã","category":"viewpoint","district":"Hoa Lư","address":"Ninh Xuân, Hoa Lư, Ninh Bình","description":"Đỉnh núi đá vôi ngắm toàn cảnh Tràng An, cung trekking ngắn và đẹp. Ít du khách, vượt qua đường mòn nông dân lên đỉnh đẹp như Hang Múa.","tags":["Điểm thu hút khách du lịch","leo núi","trekking","Tràng An"],"hours":"06:00 - 18:00","priceRange":1,"lat":20.2389,"lng":105.9389},
    // — HOMESTAY (5) —
    {"name":"Tam Coc Garden Resort","category":"homestay","district":"Hoa Lư","address":"Hải Nham, Ninh Hải, Hoa Lư, Ninh Bình","description":"Resort sinh thái boutique ven cánh đồng lúa Tam Cốc, bungalow tre nứa giữa vườn cây. Hồ bơi vô cực nhìn núi đá vôi, không gian yên bình.","tags":["Homestay","resort","sinh thái","Tam Cốc"],"hours":"24/7","priceRange":3,"lat":20.2161,"lng":105.9333},
    {"name":"Tam Coc Rice Fields Homestay","category":"homestay","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Homestay nhà sàn của người Mường giữa cánh đồng lúa, chủ nhà nấu cơm gia đình. View núi đá vôi và đồng lúa, xe đạp miễn phí thăm Tam Cốc.","tags":["Homestay","nhà sàn","Mường","đồng lúa"],"hours":"24/7","priceRange":1,"lat":20.2167,"lng":105.9319},
    {"name":"Tam Coc Banana Bungalow","category":"homestay","district":"Hoa Lư","address":"Khê Hạ, Ninh Xuân, Hoa Lư, Ninh Bình","description":"Bungalow tre nứa giữa vườn chuối ven sông Ngô Đồng, cách Tam Cốc 1km. Ăn sáng cơm Việt và cafe miễn phí trên võng nhìn đồng lúa.","tags":["Homestay","bungalow","tre nứa","sông Ngô Đồng"],"hours":"24/7","priceRange":2,"lat":20.2275,"lng":105.9408},
    {"name":"Ninh Binh Mountain Side Homestay","category":"homestay","district":"Hoa Lư","address":"Ninh Hải, Hoa Lư, Ninh Bình","description":"Homestay nằm chân núi đá vôi, view trực tiếp lên hang Múa và cánh đồng. Chủ nhà người địa phương hướng dẫn trek núi và đi xe đạp.","tags":["Homestay","núi đá","Hang Múa","local"],"hours":"24/7","priceRange":2,"lat":20.2225,"lng":105.9425},
    {"name":"Trang An Eco Homestay","category":"homestay","district":"Hoa Lư","address":"Tràng An, Hoa Lư, Ninh Bình","description":"Eco homestay ven bến thuyền Tràng An, nhà gỗ truyền thống và vườn cây. Đón thuyền tham quan Tràng An sáng sớm, không đông du khách.","tags":["Homestay","eco","Tràng An","truyền thống"],"hours":"24/7","priceRange":2,"lat":20.2581,"lng":105.8967},
  ],

  "hoi-an": [
    // — WALKING STREET / PHỐ CỔ (8) — mapped to street_food + viewpoint
    {"name":"Phố đèn lồng Nguyễn Thái Học","category":"street_food","district":"Minh An","address":"Nguyễn Thái Học, Minh An, Hội An","description":"Đường phố lung linh đèn lồng đỏ rực rỡ bên sông Hoài, dày đặc nhà hàng món Quảng và quán ăn vặt. Đi bộ tối check-in biểu tượng Hội An.","tags":["phố đi bộ","đèn lồng","phố cổ","check-in"],"hours":"17:00 - 23:00","priceRange":2,"lat":15.8775,"lng":108.3279},
    {"name":"Đường Bạch Đằng (Bờ sông Hoài)","category":"street_food","district":"Minh An","address":"Bạch Đằng, Minh An, Hội An","description":"Đường ven sông Hoài với hàng chục nhà hàng và quán cà phê view sông. Tối đèn lồng và thuyền hoa lung linh, điểm ngắm thuyền thả hoa đăng.","tags":["phố đi bộ","sông Hoài","đèn lồng","ăn uống"],"hours":"24/7","priceRange":2,"lat":15.8767,"lng":108.3296},
    {"name":"Đường Trần Phú phố cổ","category":"street_food","district":"Minh An","address":"Trần Phú, Minh An, Hội An","description":"Trục đường chính phố cổ Hội An với nhà cổ Tấn Ký, hội quán Phúc Kiến và Quảng Đông. Tối cấm xe, không khí trầm mặc cổ kính.","tags":["phố đi bộ","phố cổ","nhà cổ","hội quán"],"hours":"24/7","priceRange":2,"lat":15.8786,"lng":108.3289},
    {"name":"Chợ đêm Nguyễn Hoàng","category":"street_food","district":"Minh An","address":"Nguyễn Hoàng, Minh An, Hội An","description":"Chợ đêm phía nam sông Hoài với hàng trăm quầy ăn vặt, đèn lồng và đồ lưu niệm. Cao lầu, bánh mì Phượng và chè bắp ngay tại chợ.","tags":["chợ đêm","phố đi bộ","ăn vặt","đèn lồng"],"hours":"17:00 - 23:30","priceRange":1,"lat":15.8744,"lng":108.3308},
    {"name":"Cầu An Hội ven sông Hoài","category":"viewpoint","district":"Minh An","address":"Cầu An Hội, Minh An, Hội An","description":"Cầu bộ hành dây văng qua sông Hoài, điểm check-in tối đèn lồng và nhìn toàn cảnh phố cổ Hội An lung linh. Thuyền hoa đăng dưới chân cầu.","tags":["phố đi bộ","cầu","sông Hoài","check-in"],"hours":"24/7","priceRange":1,"lat":15.8761,"lng":108.3289},
    {"name":"Đường Lê Lợi phố cổ","category":"viewpoint","district":"Minh An","address":"Lê Lợi, Minh An, Hội An","description":"Đường nhỏ phố cổ Hội An nổi tiếng với tiệm may đo nhanh và xưởng đèn lồng truyền thống. Đông du khách Tây mua đồ may đo.","tags":["phố đi bộ","tiệm may","đèn lồng","mua sắm"],"hours":"08:00 - 22:00","priceRange":2,"lat":15.8775,"lng":108.3275},
    {"name":"Đường Hai Bà Trưng cafe","category":"viewpoint","district":"Minh An","address":"Hai Bà Trưng, Minh An, Hội An","description":"Đường nhỏ phía bắc phố cổ với dày đặc cafe phong cách Tây ba lô và Hội An xưa. Điểm tụ tập của Tây ba lô và du khách trẻ.","tags":["phố đi bộ","cafe","Tây ba lô","yên tĩnh"],"hours":"07:00 - 23:00","priceRange":2,"lat":15.8786,"lng":108.3267},
    {"name":"Phố Trần Cao Vân","category":"viewpoint","district":"Minh An","address":"Trần Cao Vân, Minh An, Hội An","description":"Đường nhỏ song song phố Trần Phú, ít du khách hơn với nhà cổ và xưởng thủ công. Cao lầu Bà Bé và bánh mì Phượng quanh khu vực.","tags":["phố đi bộ","phố cổ","local","yên tĩnh"],"hours":"24/7","priceRange":1,"lat":15.8800,"lng":108.3289},
    // — CAFE (5) — strengthen Hội An cafe coverage
    {"name":"Reaching Out Tea House","category":"cafe","district":"Minh An","address":"131 Trần Phú, Minh An, Hội An","description":"Tea house yên tĩnh do người khiếm thính phục vụ, không gian không nói chuyện. Trà Việt Nam và bánh ngọt phục vụ trong khung cảnh nhà cổ vàng.","tags":["Quán cà phê","trà","yên tĩnh","khiếm thính"],"hours":"08:00 - 21:30","priceRange":3,"lat":15.8775,"lng":108.3289},
    {"name":"Espresso Station Hội An","category":"cafe","district":"Minh An","address":"28/2 Trần Hưng Đạo, Minh An, Hội An","description":"Cafe specialty trong hẻm phố cổ, roastery rang xay tại chỗ và barista pha thử. Sân vườn nhỏ giữa nhà cổ, điểm yêu thích của dân sành cà phê.","tags":["Quán cà phê","specialty","roastery","hẻm"],"hours":"07:30 - 21:00","priceRange":3,"lat":15.8794,"lng":108.3294},
    {"name":"Phin Coffee Hội An","category":"cafe","district":"Minh An","address":"132/7 Trần Phú, Minh An, Hội An","description":"Cafe phong cách Việt cổ trong nhà cổ vàng phố Trần Phú, cà phê phin truyền thống. Ban công nhìn xuống phố đi bộ Hội An, view check-in đẹp.","tags":["Quán cà phê","cà phê phin","nhà cổ","ban công"],"hours":"07:00 - 22:00","priceRange":2,"lat":15.8775,"lng":108.3286},
    {"name":"Cocobana Cafe Hội An","category":"cafe","district":"Cẩm Thanh","address":"Đường Cửa Đại, Cẩm Thanh, Hội An","description":"Beach cafe bãi biển An Bàng, ghế lười dưới hàng dừa và cocktail trái cây. Điểm chill cả ngày sau khi tham quan phố cổ Hội An.","tags":["Quán cà phê","beach cafe","An Bàng","chill"],"hours":"07:00 - 22:30","priceRange":2,"lat":15.9264,"lng":108.3354},
    {"name":"Mia Coffee Hội An","category":"cafe","district":"Minh An","address":"20 Phan Bội Châu, Minh An, Hội An","description":"Cafe specialty của roastery Mia (Sài Gòn) phong cách industrial trong nhà cổ Hội An. Hạt cà phê single-origin Việt Nam và bánh ngọt.","tags":["Quán cà phê","specialty","Mia","roastery"],"hours":"07:00 - 22:00","priceRange":3,"lat":15.8794,"lng":108.3306},
  ],

  "vung-tau": [
    // — HOMESTAY (5) — currently only 5 total
    {"name":"Malibu Hostel Vũng Tàu","category":"homestay","district":"Thắng Tam","address":"42 Hoàng Hoa Thám, Thắng Tam, Vũng Tàu","description":"Hostel backpacker cách Bãi Sau 200m, hồ bơi tầng thượng và bar nhỏ. Dorm và phòng đôi giá rẻ, đông Tây ba lô và dân Sài Gòn cuối tuần.","tags":["Homestay","hostel","rooftop pool","backpacker"],"hours":"24/7","priceRange":2,"lat":10.3445,"lng":107.0856},
    {"name":"The Mansion Boutique Vũng Tàu","category":"homestay","district":"Thắng Nhì","address":"100B Trần Phú, Thắng Nhì, Vũng Tàu","description":"Villa cổ Pháp cải tạo thành 6 phòng nghỉ boutique, vườn nhỏ và bể bơi. Phong cách thuộc địa cách Bãi Trước 100m.","tags":["Homestay","villa","French colonial","Bãi Trước"],"hours":"24/7","priceRange":3,"lat":10.3553,"lng":107.0728},
    {"name":"Cocobeach Resort Bungalow","category":"homestay","district":"Long Hải","address":"đường Trần Phú, Phước Hải, Long Đất, Vũng Tàu","description":"Eco bungalow tre nứa ven bãi Long Hải, cách Vũng Tàu 30km. Bãi biển hoang sơ và yên tĩnh, lý tưởng cho cặp đôi và gia đình.","tags":["Homestay","bungalow","eco","Long Hải"],"hours":"24/7","priceRange":3,"lat":10.4500,"lng":107.2333},
    {"name":"Vũng Tàu Sea Breeze Homestay","category":"homestay","district":"Thắng Tam","address":"Thuỳ Vân, Thắng Tam, Vũng Tàu","description":"Nhà phố view biển Bãi Sau cải tạo thành homestay 5 phòng, sân thượng BBQ. Chủ nhà thân thiện hướng dẫn ăn hải sản và đi Núi Lớn.","tags":["Homestay","view biển","Bãi Sau","BBQ"],"hours":"24/7","priceRange":2,"lat":10.3447,"lng":107.0867},
    {"name":"Côn Đảo Homestay","category":"homestay","district":"Côn Đảo","address":"Nguyễn Huệ, Côn Đảo, Bà Rịa - Vũng Tàu","description":"Homestay địa phương trên đảo Côn Sơn, chỉ vài phút đi bộ ra biển. Chủ nhà tổ chức tour câu cá và lặn ngắm san hô, phòng nhỏ giá mềm.","tags":["Homestay","Côn Đảo","đảo","local"],"hours":"24/7","priceRange":2,"lat":8.6900,"lng":106.6080},
  ],
};
