import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

// Cache for AI-search results. The hot path is "user types the same query
// as someone else 10 minutes ago" — without a cache we'd pay the LLM bill
// twice. Hashed key keeps the column small and indexable; original query
// stored separately for debugging + cache-warming analytics.
//
// TTL is enforced at READ time by comparing createdAt + AI_CACHE_TTL_SECONDS
// against now() — no scheduled cleanup needed, GIN bloat is negligible.
@Entity({ name: 'ai_search_cache' })
export class AiSearchCache {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // sha256 hex of the normalized query (lowercased, diacritics stripped,
  // whitespace collapsed). Unique — every distinct query hashes to one row.
  @Index({ unique: true })
  @Column({ type: 'varchar', length: 64, name: 'query_hash' })
  queryHash: string;

  // Original raw query. Kept for the cache-hit log + future "popular
  // queries" surfacing. Truncated to 500 chars to keep the row small.
  @Column({ type: 'varchar', length: 500 })
  query: string;

  // Parsed structured intent from the LLM parser. Shape mirrors the
  // `ParsedIntent` type — we don't enforce the schema at the DB level
  // because the type may evolve; old cached intents are simply ignored
  // by the service when the shape changes.
  @Column({ type: 'jsonb' })
  intent: Record<string, unknown>;

  // Ordered list of venue IDs in the result. Storing IDs (not full venue
  // rows) means the cache hit re-fetches fresh venue data — so updates
  // to rating/upvotes/images propagate without needing to invalidate.
  @Column({ type: 'jsonb', name: 'venue_ids' })
  venueIds: string[];

  // DEPRECATED: pre-intro design stored a per-venue map of reasons here
  // (venueId → "Quán này hợp vì..."). New writes leave this null; old
  // rows were cleared by migration 1780000700000. Column will be dropped
  // once the 7-day TTL has guaranteed no stale-shape readers remain.
  @Column({ type: 'jsonb', name: 'reasons', nullable: true })
  reasons: Record<string, string> | null;

  // Single conversational intro that introduces the result list, e.g.
  // "Hiểu rồi, hôm nay tớ thấy bạn cần một góc yên tĩnh ở Quận 5. Mình
  // gợi ý một vài quán cafe chill có không gian thoáng đãng..."
  // Replaced per-venue reasons because the UX read better — one warm
  // opener feels like a friend recommending, while N short reasons felt
  // like AI labelling each card. Generated by the reranker in the
  // user's language.
  @Column({ type: 'text', name: 'intro', nullable: true })
  intro: string | null;

  // Whether the reranker ran. Lets the analytics tell apart pure-filter
  // queries (cheap) from vibe queries (expensive) without re-parsing.
  @Column({ type: 'boolean', name: 'used_reranker', default: false })
  usedReranker: boolean;

  // Bumped on every cache hit. Used to surface "popular queries" and to
  // bias eviction (high-traffic queries get refreshed proactively before
  // TTL expires — TODO when traffic warrants it).
  @Column({ type: 'integer', name: 'hit_count', default: 0 })
  hitCount: number;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @Column({
    type: 'timestamptz',
    name: 'last_accessed_at',
    default: () => 'now()',
  })
  lastAccessedAt: Date;
}
